# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-21 12:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hunt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('phone_number', models.IntegerField()),
                ('email_address', models.EmailField(max_length=254)),
            ],
        ),
    ]
