# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-21 13:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hunt', '0004_house_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='contact_email',
            field=models.EmailField(default=1, max_length=254),
        ),
        migrations.AddField(
            model_name='house',
            name='contact_number',
            field=models.IntegerField(default=1),
        ),
    ]
