# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-23 04:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hunt', '0006_auto_20180322_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='Description',
            field=models.TextField(max_length=1000),
        ),
    ]
